name: 'My composite Action'
description: 'A reusable composite actions that checks out code and sets up Node.js'

outputs:
  scritp-result:
    description: 'Result from the script'
    value: ${{ steps.run-script.outputs.result }}

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
  registry-url:
    required: true
  scope:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-verson: ${{ inputs.node-verson }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
    - name: Run script
      id: run-script
      run: echo "result=Success" >> "$GITHUB_OUTPUT"
      shell: bash
